import { responsiveWidth } from 'react-native-responsive-dimensions';
import { StyleSheet } from 'react-native';

const CommonStyles = {
    colors: {
        accentColor: '#0084ff',
        inactiveGreyColor: '#626262',
        lightGreyCOlor: '#eaeaea',
        separator: '#bdc3c7',
        white: 'white',
        black: 'black',
        grey: 'grey',
        red: 'red',
        onlineGreen: '#2ecc71',
        lightWhite: '#f1f1f1',
        greyMedium: '#454545',
        greyDark: '#333333',
        themeColor: '#2089DA',
        transparent: 'transparent',
        orange: '#fe8e6c',
        startColor: '#4e65ff',
        endColor: '#92effd',
        pink: '#FE3D6F',
        yellow: '#EBBA06',
        orangeRgb: '#FDF1E9',
        blueRgb: '#ECF2FF',
        pinkRgb: '#FCF2F4',
        yellowRgb: '#FDF8E5',
        green: '#59D1C4',
        greenRgb: '#E1F2F5',
        lightgreen: '#75923C',
        lightgreenRgb: '#EAF1DD',
        violet: '#60497B',
        violetRgb: '#E5E0EC',
        lightOrange: '#ffb284',
        lightPink: '#e79796',
        imgStartColor: '#9dc3e2',
        imgEndColor: '#9dd2d8',
        offWhite: '#f5f5f5',
    },
    fonts: {
        FONT_REGULAR: 'Poppins-Regular',
        FONT_MEDIUM: 'Poppins-Medium',
        FONT_LIGHT: 'Poppins-Light',
        FONT_THIN: 'Poppins-Thin',
        FONT_SEMI_BOLD: 'Poppins-SemiBold',
        FONT_BOLD: 'Poppins-Bold',
    },
    style: StyleSheet.create({
        container: {
            flex: 1,
            backgroundColor: '#f5f5f5',
        },
        center: {
            alignItems: 'center',
        },
        right: {
            alignItems: 'flex-end',
        },
        curveView: {
            backgroundColor: '#f4f4f4',
            flex: 1,
            paddingLeft: responsiveWidth(3),
            paddingRight: responsiveWidth(3),
        },
        messageTxt: {
            fontFamily: 'Poppins-SemiBold',
            fontSize: 18,
            color: '#000000',
            alignSelf: 'center',
        },
        activityIndicator: {
            position: 'absolute',
            left: 0,
            right: 0,
            top: 0,
            bottom: 0,
            opacity: 0.5,
            backgroundColor: 'black',
            justifyContent: 'center',
            alignItems: 'center'
        }
    }),

    strings: {
        prints: 'Print',
        createOrder: 'Create Order',
        welcome: 'Welcome to RMS',
        wishesMsg:
            'Good morning is not just a word, it’s an action and a belief to live the entire day well. Morning is the time when you set the tone for the rest of the day. Set it right! Have A Nice Day!',
        hey: 'Hello',
        name: 'David Warner',
        email: 'david@gmail.com',
        tab_Home: 'Home',
        tab_Order: 'Orders',
        tab_more: 'More',
        more_profile: 'Profile',
        more_routes: 'Routes',
        more_stores: 'Stores',
        more_products: 'Products',
        more_transfers: 'Transfers',
        more_reports: 'Reports',
        more_orders: 'Orders List',
        signout: 'SignOut',
        more: 'More',
        store: 'Stores',
        routes: 'Routes',
        products: 'Products',
        transfers: 'Transfer Products',
        orders: 'Orders',
        store_details: 'Store Details',
        profile: 'Profile',
        orderDetails: 'Order Details',
        createOrderConfirm: 'Create Order Confirmation',
        sale: 'Sale',
        Buyback: 'Buyback',
        damaged: 'Damaged',
        crate_order: 'Create Order',
        empty_message: 'Data Not Found',
        cart: 'Cart',
        logout: 'Logout',
        printer: 'Select Printer',
        loading: 'Loading..',
        transfer: 'Transfer',
        noProducts: 'No Products found to Transfer',
        getWeeklyReport: 'Get Weekly Report',
        empty_routes: "No routes found",
        empty_store: "No stores found",
        empty_orders: "No orders found",
        empty_products: "No products found"
    },
};

export default CommonStyles;
